#ifndef __DATA_TYPES__
#define __DATA_TYPES__

enum E_ActorTypes {
	TYPE_PLAYER,
	TYPE_GREEN_SQUARE, TYPE_BLUE_SQUARE, TYPE_RED_SQUARE,
	TYPE_GREEN_TRIANGLE, TYPE_BLUE_TRIANGLE, TYPE_RED_TRIANGLE,
	TYPE_GREEN_DISC, TYPE_BLUE_DISC, TYPE_RED_DISC,
	NB_TYPES
};

#endif
